[versions]
kotlin = "1.8.22"
kotlinx-coroutines = "1.7.3"

[libraries]
annotations  = { module = "org.jetbrains:annotations", version = "23.0.0" }
guava        = { module = "com.google.guava:guava", version = "31.1-jre" }
gson         = { module = "com.google.code.gson:gson", version = "2.9.0" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
